### ISSUE TITLE
[OTHER] Center align the welcome heading

### ISSUE THREAD

**Issue by niteshseram** [nhcommunity/homepage#19]
# Other Issue

## Describe the issue
The welcome heading is currently left align. So, we can fix it to align it center.
I would love to work on this.

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `public/index.css` file:
  - On line 70, replace `text-align: left;` with `justify-content: center;`

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by schmelto** [comment]
Think this one is already fixed

**Comment by Panquesito7** [comment]
Yep, it's fixed. Thanks for pointing that out. 🙂
