### ISSUE TITLE
[BUG] Profile image missing

### ISSUE THREAD

**Issue by SashoStoichkov** [nhcommunity/homepage#20]
# Bug Report

## Describe the bug

The link [on this line](https://github.com/nhcommunity/homepage/blob/e86214c02a712cba234f821a859aaf55fa0d1cbe/index.html#L74) is either wrong or there is a problem with the CDN.

## Screenshots

![image](https://user-images.githubusercontent.com/24972335/123995647-3c6e7500-d9d7-11eb-8d23-a8ae96f3baba.png)
![image](https://user-images.githubusercontent.com/24972335/123996085-a424c000-d9d7-11eb-8783-d4ccf27748ef.png)

**Comment by nhcarrigan** [comment]
Ah yeah I replaced the profile image.

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `index.html` file
  - On line 74:
  - The `src` link should be updated to `https://cdn.nhcarrigan.com/content/profile-transparent.png`.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by Prasanna0908** [comment]
Hi. I am a beginner and I haven't contributed to any open source project before. I am interested in addressing this issue. So what I understand is I have to change the source of the line in the index.html file on line 74. Is that correct? Can you please assign me this issue?

**Comment by nhcarrigan** [comment]
That is correct 😁 

I've assigned you the issue. Feel free to let us know if you have any questions.
