### ISSUE TITLE
[OTHER] Replace (link) with actual link 

### ISSUE THREAD

**Issue by Sonichigo** [nhcommunity/homepage#27]
### What would you like to share?

In our community website, at certain places there is word **link** which has to be updated with an actual link's in respect to the context of the sentence.

Places of correction
- [ ] In our community section
- [ ] In our discussion section 
       1. Resources
       2. Help

### Additional information

![image](https://user-images.githubusercontent.com/53110238/131431380-744371d7-df65-4213-a7b6-1f5eae4c0c73.png)

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- On line 40 of the [index.html](https://github.com/nhcommunity/homepage/blob/235da2703edab21dd5b267561a6486bbed26c80c/index.html#L40) file:
  - Replace `come meet them here (link)` with `come meet them <a href="https://chat.nhcarrigan.com" target="_blank" rel="noopener noreferrer">in our server</a>.`

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by Mannuel25** [comment]
I'd love to take up this issue @nhcarrigan

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by Mannuel25** [comment]
![WhatsApp Image 2021-09-28 at 14 31 06](https://user-images.githubusercontent.com/68563757/135101420-f640ffb3-8f31-4fa7-b7cb-ca25aafa1a22.jpeg)

Our discussion section also contains some not-fixed links, like **Resources** and **Help**. I wanted to add the links, but I couldn't find them.

**Comment by nhcarrigan** [comment]
We can look at those in a separate issue. 🙂

**Comment by Mannuel25** [comment]
> We can look at those in a separate issue. slightly_smiling_face

Alright, I will open a new issue for that.

**Comment by ReubenMenezes** [comment]
So are we closing this issue?

**Comment by nhcarrigan** [comment]
Yeah let's close this one.
